# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Fam.ly - iOS Edition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fam.ly - iOS Edition
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

end
